# supervisor
# VERSION 

FROM vicanso/io.js

MAINTAINER "vicansocanbico@gmail.com"

CMD cd /supervisor && npm install --production --registry=https://registry.npm.taobao.org && pm2 start pm2.json && pm2 logs